Drop EL6 and Debian 8
theforeman/puppet-tftp pull request #122
Opened 2021-07-15 12:16 UTC by ehelms

2021-07-15 12:19 UTC, ekohl requested changes
I was looking at it and there's more EOL: Ubuntu 16.04 is EOL since April. Also Fedora < 33.

We can also drop some files in `data/`

2021-07-19 14:42 UTC, ekohl commented on metadata.json
> +        "34"
```suggestion
        "34"
      ]
```

2021-07-19 16:40 UTC, ekohl commented
Fedora 33 fails because there are no packages and Fedora 34 fails because it tries to install ntpdate which is no longer available in recent Fedora. For Fedora 34 we'll need an updated beaker: https://github.com/voxpupuli/beaker/pull/1709

2021-07-20 04:09 UTC, evgeni commented
The title shouldn't say you're dropping 18.04, that gave me a brief shock. 16.04 is safe to drop.

2021-07-20 09:04 UTC, ekohl commented
Turns out I was looking in the wrong place: https://github.com/voxpupuli/beaker-docker/pull/48 should fix Fedora 34.

2021-07-20 14:56 UTC, ehelms commented
> The title shouldn't say you're dropping 18.04, that gave me a brief shock. 16.04 is safe to drop.

The commit message was right at least :)

2021-07-20 19:03 UTC, ekohl commented
Given Fedora 33 and 34 are failing, perhaps we should roll back that change and stick to the existing values? Then we at least have green builds.

Otherwise :+1:

2021-07-20 19:37 UTC, ehelms commented
Updated and left Fedora alone

2021-07-20 21:52 UTC, ekohl approved these changes

2021-07-20 21:53 UTC, merged